// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exchange_rates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (currency, rate_date, rate, created_at)
VALUES ($1, $2, $3, NOW())
RETURNING currency, rate_date, rate, created_at
`

type CreateExchangeRateParams struct {
	Currency string         `db:"currency"`
	RateDate pgtype.Date    `db:"rate_date"`
	Rate     pgtype.Numeric `db:"rate"`
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, createExchangeRate, arg.Currency, arg.RateDate, arg.Rate)
	var i ExchangeRate
	err := row.Scan(
		&i.Currency,
		&i.RateDate,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestExchangeRateBeforeDate = `-- name: GetLatestExchangeRateBeforeDate :one
SELECT currency, rate_date, rate
FROM exchange_rates
WHERE currency = $1
  AND rate_date <= $2
ORDER BY rate_date DESC
LIMIT 1
`

type GetLatestExchangeRateBeforeDateParams struct {
	Currency string      `db:"currency"`
	RateDate pgtype.Date `db:"rate_date"`
}

type GetLatestExchangeRateBeforeDateRow struct {
	Currency string         `db:"currency"`
	RateDate pgtype.Date    `db:"rate_date"`
	Rate     pgtype.Numeric `db:"rate"`
}

func (q *Queries) GetLatestExchangeRateBeforeDate(ctx context.Context, arg GetLatestExchangeRateBeforeDateParams) (GetLatestExchangeRateBeforeDateRow, error) {
	row := q.db.QueryRow(ctx, getLatestExchangeRateBeforeDate, arg.Currency, arg.RateDate)
	var i GetLatestExchangeRateBeforeDateRow
	err := row.Scan(&i.Currency, &i.RateDate, &i.Rate)
	return i, err
}
