// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExchangeRate struct {
	Currency  string           `db:"currency"`
	RateDate  pgtype.Date      `db:"rate_date"`
	Rate      pgtype.Numeric   `db:"rate"`
	CreatedAt pgtype.Timestamp `db:"created_at"`
}

type Purchase struct {
	ID              pgtype.UUID      `db:"id"`
	Description     string           `db:"description"`
	TransactionDate pgtype.Date      `db:"transaction_date"`
	AmountUsdCents  int64            `db:"amount_usd_cents"`
	CreatedAt       pgtype.Timestamp `db:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at"`
}
