// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (id, description, transaction_date, amount_usd_cents, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, description, transaction_date, amount_usd_cents, created_at, updated_at
`

type CreatePurchaseParams struct {
	ID              pgtype.UUID `db:"id"`
	Description     string      `db:"description"`
	TransactionDate pgtype.Date `db:"transaction_date"`
	AmountUsdCents  int64       `db:"amount_usd_cents"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRow(ctx, createPurchase,
		arg.ID,
		arg.Description,
		arg.TransactionDate,
		arg.AmountUsdCents,
	)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.TransactionDate,
		&i.AmountUsdCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseByID = `-- name: GetPurchaseByID :one
SELECT id, description, transaction_date, amount_usd_cents, created_at, updated_at
FROM purchases
WHERE id = $1
`

func (q *Queries) GetPurchaseByID(ctx context.Context, id pgtype.UUID) (Purchase, error) {
	row := q.db.QueryRow(ctx, getPurchaseByID, id)
	var i Purchase
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.TransactionDate,
		&i.AmountUsdCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRateForDate = `-- name: GetRateForDate :one
SELECT currency, rate_date, rate
FROM exchange_rates
WHERE currency = $1 
  AND rate_date <= $2
  AND rate_date >= ($2::date - interval '6 months')
ORDER BY rate_date DESC
LIMIT 1
`

type GetRateForDateParams struct {
	Currency string      `db:"currency"`
	RateDate pgtype.Date `db:"rate_date"`
}

type GetRateForDateRow struct {
	Currency string         `db:"currency"`
	RateDate pgtype.Date    `db:"rate_date"`
	Rate     pgtype.Numeric `db:"rate"`
}

func (q *Queries) GetRateForDate(ctx context.Context, arg GetRateForDateParams) (GetRateForDateRow, error) {
	row := q.db.QueryRow(ctx, getRateForDate, arg.Currency, arg.RateDate)
	var i GetRateForDateRow
	err := row.Scan(&i.Currency, &i.RateDate, &i.Rate)
	return i, err
}
